version: 2.1

jobs:
  build:
    docker:
      - image: node:18.18.0

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build and Test
          command: node --version && npm --version

      - run:
          name: Deploy
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - build
