version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build and Test
          command: npm test

      - run:
          name: Deploy
          command: echo "Deployed successfully"

workflows:
  version: 2
  build:
    jobs:
      - build
