name: Api Testing CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }} # branch chosen in Actions UI

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm test

      - name: Deploy
        run: echo "Deployed successfully to ${{ github.event.inputs.environment }}"
