name: Api Testing CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm test

      - name: Deploy
        run: echo "Deployed successfully"
